# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/clock_divider/clock_divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_divider || ORIG_REF_NAME==clock_divider}]

# XDC: ip/clock_divider/clock_divider_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_divider || ORIG_REF_NAME==clock_divider}] {/inst }]/inst ]]

# XDC: ip/clock_divider/clock_divider.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_divider || ORIG_REF_NAME==clock_divider}] {/inst }]/inst ]]

# XDC: ip/clock_divider/clock_divider_ooc.xdc
