# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/lab3sound/lab3sound.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/lab3sound/lab3sound.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/lab3sound/lab3sound.srcs/sources_1/new/file_gen.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/adau1761_configuraiton_data.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/ADAU1761_interface.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/i2c.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/i2s_data_interface.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/clocking.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/adau1761_izedboard.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/i3c2.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/dsp_block.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/low_pass_moving_sum.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/low_pass_moving_average.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/tb_adau1761_test.vhd
  /afs/ece.cmu.edu/usr/cmbarker/Downloads/dsp_base_project/adau1761_test.vhd
}
read_xdc /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/lab3sound/lab3sound.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/lab3sound/lab3sound.srcs/constrs_1/new/constraints.xdc]

synth_design -top adau1761_test -part xc7z020clg484-1
write_checkpoint -noxdef adau1761_test.dcp
catch { report_utilization -file adau1761_test_utilization_synth.rpt -pb adau1761_test_utilization_synth.pb }
