#!/bin/sh -f
######################################################################
#
# File name : compile.sh
# Created on: Thu Oct 15 22:04:07 EDT 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

# installation path setting
bin_path="/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set vhdlan command line args
vhdlan_opts="-full64"

# set vlogan command line args
vlogan_opts="-full64"

# compile design source files
$bin_path/vlogan $vlogan_opts -sverilog -Xcheck_p1800_2009=char -work xil_defaultlib  \
"$origin_dir/../../../maria.srcs/sources_1/new/timing_ctrl.sv" \
"$origin_dir/../../../maria.srcs/sources_1/new/line_ram.sv" \
"$origin_dir/../../../maria.srcs/sources_1/new/dma_ctrl.sv" \
"$origin_dir/../../../maria.srcs/sources_1/new/memory_map.sv" \
"$origin_dir/../../../../vga.sv" \
"$origin_dir/../../../maria.srcs/sources_1/new/maria.sv" \
2>&1 | tee -a vlogan.log

$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib  \
"$origin_dir/../../../maria.srcs/sources_1/ip/clock_divider/clock_divider_clk_wiz.v" \
"$origin_dir/../../../maria.srcs/sources_1/ip/clock_divider/clock_divider.v" \
2>&1 | tee -a vlogan.log

$bin_path/vlogan $vlogan_opts -sverilog -Xcheck_p1800_2009=char -work xil_defaultlib  \
"$origin_dir/../../../maria.srcs/sources_1/new/top.sv" \
"$origin_dir/../../../maria.srcs/sources_1/new/tb.sv" \
2>&1 | tee -a vlogan.log


# compile glbl module
$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib "glbl.v" 2>&1 | tee -a vlogan.log
