#!/bin/sh -f
######################################################################
#
# File name : elaborate.sh
# Created on: Thu Oct 15 22:04:08 EDT 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################

# installation path setting
bin_path="/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin"

# set vcs command line args
vcs_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"

# run elaboration
$bin_path/vcs $vcs_opts xil_defaultlib.tb xil_defaultlib.glbl -o tb_simv
