# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.srcs/sources_1/ip/dll_img_ram/dll_img_ram.xci
# IP: The module: 'dll_img_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.srcs/sources_1/ip/dll_img_ram/dll_img_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dll_img_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.srcs/sources_1/ip/dll_img_ram/dll_img_ram.xci
# IP: The module: 'dll_img_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.srcs/sources_1/ip/dll_img_ram/dll_img_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dll_img_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
