set_property PACKAGE_PIN AB19 [get_ports {BLUE[3]}]
set_property PACKAGE_PIN AB20 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN Y20 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN Y21 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN AA21 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN AB21 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN AA22 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN AB22 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN V18 [get_ports {RED[3]}]
set_property PACKAGE_PIN V19 [get_ports {RED[2]}]
set_property PACKAGE_PIN U20 [get_ports {RED[1]}]
set_property PACKAGE_PIN V20 [get_ports {RED[0]}]
set_property PACKAGE_PIN Y9 [get_ports CLOCK_PLL]
set_property PACKAGE_PIN AA19 [get_ports HSync]
set_property PACKAGE_PIN Y19 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports CLOCK_PLL]
set_property IOSTANDARD LVCMOS18 [get_ports HSync]
set_property IOSTANDARD LVCMOS18 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[0]}]



set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS18 [get_ports AC_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SDA]


set_property IOSTANDARD LVCMOS18 [get_ports {ld[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[0]}]
set_property PACKAGE_PIN U14 [get_ports {ld[7]}]
set_property PACKAGE_PIN U19 [get_ports {ld[6]}]
set_property PACKAGE_PIN W22 [get_ports {ld[5]}]
set_property PACKAGE_PIN V22 [get_ports {ld[4]}]
set_property PACKAGE_PIN U21 [get_ports {ld[3]}]
set_property PACKAGE_PIN U22 [get_ports {ld[2]}]
set_property PACKAGE_PIN T21 [get_ports {ld[1]}]
set_property PACKAGE_PIN T22 [get_ports {ld[0]}]

set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
set_property PACKAGE_PIN R16 [get_ports down]
set_property PACKAGE_PIN P16 [get_ports fire]
set_property PACKAGE_PIN N15 [get_ports left]
set_property PACKAGE_PIN R18 [get_ports right]
set_property PACKAGE_PIN T18 [get_ports up]

set_property PACKAGE_PIN F22 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

set_property IOSTANDARD LVCMOS18 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports up]
set_property IOSTANDARD LVCMOS18 [get_ports right]
set_property IOSTANDARD LVCMOS18 [get_ports down]
set_property IOSTANDARD LVCMOS18 [get_ports fire]
set_property IOSTANDARD LVCMOS18 [get_ports left]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list console/divider/inst/CLOCK_100]]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {PBin[0]} {PBin[1]}]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {PAin[4]} {PAin[5]} {PAin[6]} {PAin[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {console/maria_inst/timing_ctrl_inst/row[0]} {console/maria_inst/timing_ctrl_inst/row[1]} {console/maria_inst/timing_ctrl_inst/row[2]} {console/maria_inst/timing_ctrl_inst/row[3]} {console/maria_inst/timing_ctrl_inst/row[4]} {console/maria_inst/timing_ctrl_inst/row[5]} {console/maria_inst/timing_ctrl_inst/row[6]} {console/maria_inst/timing_ctrl_inst/row[7]} {console/maria_inst/timing_ctrl_inst/row[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {console/maria_inst/timing_ctrl_inst/state[0]} {console/maria_inst/timing_ctrl_inst/state[1]} {console/maria_inst/timing_ctrl_inst/state[2]} {console/maria_inst/timing_ctrl_inst/state[3]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {console/maria_AB_out[0]} {console/maria_AB_out[1]} {console/maria_AB_out[2]} {console/maria_AB_out[3]} {console/maria_AB_out[4]} {console/maria_AB_out[5]} {console/maria_AB_out[6]} {console/maria_AB_out[7]} {console/maria_AB_out[8]} {console/maria_AB_out[9]} {console/maria_AB_out[10]} {console/maria_AB_out[11]} {console/maria_AB_out[12]} {console/maria_AB_out[13]} {console/maria_AB_out[14]} {console/maria_AB_out[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {console/read_DB[0]} {console/read_DB[1]} {console/read_DB[2]} {console/read_DB[3]} {console/read_DB[4]} {console/read_DB[5]} {console/read_DB[6]} {console/read_DB[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {console/maria_inst/dma_ctrl_inst/OFFSET[0]} {console/maria_inst/dma_ctrl_inst/OFFSET[1]} {console/maria_inst/dma_ctrl_inst/OFFSET[2]} {console/maria_inst/dma_ctrl_inst/OFFSET[3]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {console/maria_inst/dma_ctrl_inst/ZP_saved_next[0]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[1]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[2]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[3]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[4]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[5]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[6]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[7]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[8]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[9]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[10]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[11]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[12]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[13]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[14]} {console/maria_inst/dma_ctrl_inst/ZP_saved_next[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {console/maria_inst/dma_ctrl_inst/PP[0]} {console/maria_inst/dma_ctrl_inst/PP[1]} {console/maria_inst/dma_ctrl_inst/PP[2]} {console/maria_inst/dma_ctrl_inst/PP[3]} {console/maria_inst/dma_ctrl_inst/PP[4]} {console/maria_inst/dma_ctrl_inst/PP[5]} {console/maria_inst/dma_ctrl_inst/PP[6]} {console/maria_inst/dma_ctrl_inst/PP[7]} {console/maria_inst/dma_ctrl_inst/PP[8]} {console/maria_inst/dma_ctrl_inst/PP[9]} {console/maria_inst/dma_ctrl_inst/PP[10]} {console/maria_inst/dma_ctrl_inst/PP[11]} {console/maria_inst/dma_ctrl_inst/PP[12]} {console/maria_inst/dma_ctrl_inst/PP[13]} {console/maria_inst/dma_ctrl_inst/PP[14]} {console/maria_inst/dma_ctrl_inst/PP[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {console/maria_inst/dma_ctrl_inst/dp_state[0]} {console/maria_inst/dma_ctrl_inst/dp_state[1]} {console/maria_inst/dma_ctrl_inst/dp_state[2]} {console/maria_inst/dma_ctrl_inst/dp_state[3]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list console/maria_drive_AB]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list console/ctrl/lock_out]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list console/maria_inst/dp_dma_start]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list console/maria_inst/zp_dma_start]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLOCK_100]
