set_property PACKAGE_PIN AB19 [get_ports {BLUE[3]}]
set_property PACKAGE_PIN AB20 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN Y20 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN Y21 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN AA21 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN AB21 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN AA22 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN AB22 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN V18 [get_ports {RED[3]}]
set_property PACKAGE_PIN V19 [get_ports {RED[2]}]
set_property PACKAGE_PIN U20 [get_ports {RED[1]}]
set_property PACKAGE_PIN V20 [get_ports {RED[0]}]
set_property PACKAGE_PIN Y9 [get_ports CLOCK_PLL]
set_property PACKAGE_PIN AA19 [get_ports HSync]
set_property PACKAGE_PIN Y19 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports CLOCK_PLL]
set_property IOSTANDARD LVCMOS18 [get_ports HSync]
set_property IOSTANDARD LVCMOS18 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[0]}]



set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS18 [get_ports AC_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SDA]


set_property IOSTANDARD LVCMOS18 [get_ports {ld[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[0]}]
set_property PACKAGE_PIN U14 [get_ports {ld[7]}]
set_property PACKAGE_PIN U19 [get_ports {ld[6]}]
set_property PACKAGE_PIN W22 [get_ports {ld[5]}]
set_property PACKAGE_PIN V22 [get_ports {ld[4]}]
set_property PACKAGE_PIN U21 [get_ports {ld[3]}]
set_property PACKAGE_PIN U22 [get_ports {ld[2]}]
set_property PACKAGE_PIN T21 [get_ports {ld[1]}]
set_property PACKAGE_PIN T22 [get_ports {ld[0]}]

set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]
set_property PACKAGE_PIN P16 [get_ports PB_CENTER]
set_property PACKAGE_PIN R16 [get_ports PB_DOWN]
set_property PACKAGE_PIN N15 [get_ports PB_LEFT]
set_property PACKAGE_PIN R18 [get_ports PB_RIGHT]
set_property PACKAGE_PIN T18 [get_ports PB_UP]


set_property IOSTANDARD LVCMOS25 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports PB_UP]
set_property IOSTANDARD LVCMOS25 [get_ports PB_RIGHT]
set_property IOSTANDARD LVCMOS25 [get_ports PB_LEFT]
set_property IOSTANDARD LVCMOS25 [get_ports PB_CENTER]
set_property IOSTANDARD LVCMOS25 [get_ports PB_DOWN]






set_property PACKAGE_PIN K21 [get_ports {ctrl_0_fmc[0]}]
set_property PACKAGE_PIN J20 [get_ports {ctrl_0_fmc[1]}]
set_property PACKAGE_PIN B20 [get_ports {ctrl_0_fmc[2]}]
set_property PACKAGE_PIN B19 [get_ports {ctrl_0_fmc[3]}]
set_property PACKAGE_PIN C20 [get_ports {ctrl_0_fmc[4]}]
set_property PACKAGE_PIN D20 [get_ports {ctrl_0_fmc[5]}]
set_property PACKAGE_PIN G16 [get_ports {ctrl_0_fmc[6]}]
set_property PACKAGE_PIN G15 [get_ports {ctrl_1_fmc[0]}]
set_property PACKAGE_PIN G21 [get_ports {ctrl_1_fmc[1]}]
set_property PACKAGE_PIN G20 [get_ports {ctrl_1_fmc[2]}]
set_property PACKAGE_PIN E20 [get_ports {ctrl_1_fmc[3]}]
set_property PACKAGE_PIN E19 [get_ports {ctrl_1_fmc[4]}]
set_property PACKAGE_PIN F19 [get_ports {ctrl_1_fmc[5]}]
set_property PACKAGE_PIN G19 [get_ports {ctrl_1_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[0]}]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list console/divider/inst/CLOCK_100]]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {console/vga_row[0]} {console/vga_row[1]} {console/vga_row[2]} {console/vga_row[3]} {console/vga_row[4]} {console/vga_row[5]} {console/vga_row[6]} {console/vga_row[7]} {console/vga_row[8]} {console/vga_row[9]}]]
create_debug_port u_ila_0 probe
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {console/vga_col[0]} {console/vga_col[1]} {console/vga_col[2]} {console/vga_col[3]} {console/vga_col[4]} {console/vga_col[5]} {console/vga_col[6]} {console/vga_col[7]} {console/vga_col[8]} {console/vga_col[9]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {console/uv_tia[0]} {console/uv_tia[1]} {console/uv_tia[2]} {console/uv_tia[3]} {console/uv_tia[4]} {console/uv_tia[5]} {console/uv_tia[6]} {console/uv_tia[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list console/tia_hsync_kept]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list console/tia_vsync_kept]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list console/vga_hsync_kept]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list console/vga_vsync_kept]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list console/cpu_inst/rdy_in]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLOCK_100]
