set_property PACKAGE_PIN AB19 [get_ports {BLUE[3]}]
set_property PACKAGE_PIN AB20 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN Y20 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN Y21 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN AA21 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN AB21 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN AA22 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN AB22 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN V18 [get_ports {RED[3]}]
set_property PACKAGE_PIN V19 [get_ports {RED[2]}]
set_property PACKAGE_PIN U20 [get_ports {RED[1]}]
set_property PACKAGE_PIN V20 [get_ports {RED[0]}]
set_property PACKAGE_PIN Y9 [get_ports CLOCK_PLL]
set_property PACKAGE_PIN AA19 [get_ports HSync]
set_property PACKAGE_PIN Y19 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports CLOCK_PLL]
set_property IOSTANDARD LVCMOS18 [get_ports HSync]
set_property IOSTANDARD LVCMOS18 [get_ports VSync]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BLUE[0]}]



set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_ADR1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS18 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS18 [get_ports AC_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports AC_SDA]


set_property IOSTANDARD LVCMOS18 [get_ports {ld[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ld[0]}]
set_property PACKAGE_PIN U14 [get_ports {ld[7]}]
set_property PACKAGE_PIN U19 [get_ports {ld[6]}]
set_property PACKAGE_PIN W22 [get_ports {ld[5]}]
set_property PACKAGE_PIN V22 [get_ports {ld[4]}]
set_property PACKAGE_PIN U21 [get_ports {ld[3]}]
set_property PACKAGE_PIN U22 [get_ports {ld[2]}]
set_property PACKAGE_PIN T21 [get_ports {ld[1]}]
set_property PACKAGE_PIN T22 [get_ports {ld[0]}]

set_property PACKAGE_PIN M15 [get_ports {sw[7]}]
set_property PACKAGE_PIN H17 [get_ports {sw[6]}]
set_property PACKAGE_PIN H18 [get_ports {sw[5]}]
set_property PACKAGE_PIN H19 [get_ports {sw[4]}]
set_property PACKAGE_PIN F21 [get_ports {sw[3]}]
set_property PACKAGE_PIN H22 [get_ports {sw[2]}]
set_property PACKAGE_PIN G22 [get_ports {sw[1]}]
set_property PACKAGE_PIN F22 [get_ports {sw[0]}]
set_property PACKAGE_PIN P16 [get_ports PB_CENTER]
set_property PACKAGE_PIN R16 [get_ports PB_DOWN]
set_property PACKAGE_PIN N15 [get_ports PB_LEFT]
set_property PACKAGE_PIN R18 [get_ports PB_RIGHT]
set_property PACKAGE_PIN T18 [get_ports PB_UP]


set_property IOSTANDARD LVCMOS25 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports PB_UP]
set_property IOSTANDARD LVCMOS25 [get_ports PB_RIGHT]
set_property IOSTANDARD LVCMOS25 [get_ports PB_LEFT]
set_property IOSTANDARD LVCMOS25 [get_ports PB_CENTER]
set_property IOSTANDARD LVCMOS25 [get_ports PB_DOWN]






set_property PACKAGE_PIN K21 [get_ports {ctrl_0_fmc[0]}]
set_property PACKAGE_PIN J20 [get_ports {ctrl_0_fmc[1]}]
set_property PACKAGE_PIN B20 [get_ports {ctrl_0_fmc[2]}]
set_property PACKAGE_PIN B19 [get_ports {ctrl_0_fmc[3]}]
set_property PACKAGE_PIN C20 [get_ports {ctrl_0_fmc[4]}]
set_property PACKAGE_PIN D20 [get_ports {ctrl_0_fmc[5]}]
set_property PACKAGE_PIN G16 [get_ports {ctrl_0_fmc[6]}]
set_property PACKAGE_PIN G15 [get_ports {ctrl_1_fmc[0]}]
set_property PACKAGE_PIN G21 [get_ports {ctrl_1_fmc[1]}]
set_property PACKAGE_PIN G20 [get_ports {ctrl_1_fmc[2]}]
set_property PACKAGE_PIN E20 [get_ports {ctrl_1_fmc[3]}]
set_property PACKAGE_PIN E19 [get_ports {ctrl_1_fmc[4]}]
set_property PACKAGE_PIN F19 [get_ports {ctrl_1_fmc[5]}]
set_property PACKAGE_PIN G19 [get_ports {ctrl_1_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_0_fmc[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ctrl_1_fmc[0]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list console/divider/inst/CLOCK_100]]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {console/cpu_inst/core/DIHOLD[0]} {console/cpu_inst/core/DIHOLD[1]} {console/cpu_inst/core/DIHOLD[2]} {console/cpu_inst/core/DIHOLD[3]} {console/cpu_inst/core/DIHOLD[4]} {console/cpu_inst/core/DIHOLD[5]} {console/cpu_inst/core/DIHOLD[6]} {console/cpu_inst/core/DIHOLD[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {console/core_AB_out[0]} {console/core_AB_out[1]} {console/core_AB_out[2]} {console/core_AB_out[3]} {console/core_AB_out[4]} {console/core_AB_out[5]} {console/core_AB_out[6]} {console/core_AB_out[7]} {console/core_AB_out[8]} {console/core_AB_out[9]} {console/core_AB_out[10]} {console/core_AB_out[11]} {console/core_AB_out[12]} {console/core_AB_out[13]} {console/core_AB_out[14]} {console/core_AB_out[15]}]]
create_debug_port u_ila_0 probe
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {console/pc_temp[0]} {console/pc_temp[1]} {console/pc_temp[2]} {console/pc_temp[3]} {console/pc_temp[4]} {console/pc_temp[5]} {console/pc_temp[6]} {console/pc_temp[7]} {console/pc_temp[8]} {console/pc_temp[9]} {console/pc_temp[10]} {console/pc_temp[11]} {console/pc_temp[12]} {console/pc_temp[13]} {console/pc_temp[14]} {console/pc_temp[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLOCK_100]
