/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan +v2k -nc -full64 -work secureip -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/secureip/.cxl.verilog.secureip.secureip.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan  -full64 -work secureip -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/secureip/.cxl.verilog.axi_bfm.secureip.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vhdlan -nc -full64 -work unisim -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unisim/.cxl.vhdl.unisim.unisim.lin64.cmf -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unisim/.cxl.vhdl.secureip_vhdl_unisim.unisim.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vhdlan -nc -full64 -work unimacro -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unimacro/.cxl.vhdl.unimacro.unimacro.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vhdlan -nc -full64 -work unifast -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unifast/.cxl.vhdl.unifast.unifast.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan +v2k -nc -full64 -work unisims_ver -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unisims_ver/.cxl.verilog.unisim.unisims_ver.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan +v2k -nc -full64 -work unimacro_ver -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unimacro_ver/.cxl.verilog.unimacro.unimacro_ver.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan +v2k -nc -full64 -work unifast_ver -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/unifast_ver/.cxl.verilog.unifast.unifast_ver.lin64.cmf
/afs/ece.cmu.edu/support/synopsys/synopsys/share/image/usr/local/synopsys/vcs-mx_vF-2011.12-SP1/bin/vlogan +v2k -nc +define+XIL_TIMING -full64 -work simprims_ver -f /afs/ece.cmu.edu/usr/cmbarker/Private/Atari7800/maria/maria.cache/compile_simlib/simprims_ver/.cxl.verilog.simprim.simprims_ver.lin64.cmf
